name: Tests

on:
  push:
    branches: [ "main", "backend-dev-imh", "backend-dev-marco", "frontend-dev-al"]
  pull_request:
    branches: [ "main", "backend-dev-imh", "backend-dev-marco", "frontend-dev-al"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x, 18.x, 19.x, 20.x]
        mongodb-version: ['5.0', '6.0']

    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.9.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Install dependencies 
      run: npm run installServer
    
    - name: Running tests
      run: npm run test:server